data_file = open("data.txt", 'a')
print('              --BTX--          ')
print('  ')
print('1. Create Account')
print('2. Sign In')
operation = input('Num: ')
while operation != '1':
	if operation == '2':
		log1 = input('Enter Login: ')
		log2 = input('Enter Pass: ')
	print('Incorrect num')
	operation = input('Num: ')
log = input('Create login: ')
pas = input('Create pass: ')
data_file = open("data.txt", 'a')
data_file.write(log)
data_file.write('\n')
data_file.write(pas)
data_file.write('\n')
data_file.write('——————————————')
data_file.write('\n')
data_file.close()

print('Hello!', log)
email = input('Enter mail: ')
print('A message has been \nsent to your mail')
print('/read - Read New Message')
com2 = input(': ')
while com2 != '/read':
	print('Incorrect commmand')
	com2 = input(': ')
print('Account', log, 'Created')

input()